// <auto-generated />
using System;
using Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828100248_AddIeltsVocabularyImport")]
    partial class AddIeltsVocabularyImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_courses_created_by_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_slug");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.HskMockTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collection_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HskUrl")
                        .HasColumnType("text")
                        .HasColumnName("hsk_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ListeningAnswerUrl")
                        .HasColumnType("text")
                        .HasColumnName("listening_answer_url");

                    b.Property<string>("ListeningUrl")
                        .HasColumnType("text")
                        .HasColumnName("listening_url");

                    b.Property<string>("ReadingAnswerUrl")
                        .HasColumnType("text")
                        .HasColumnName("reading_answer_url");

                    b.Property<string>("ReadingUrl")
                        .HasColumnType("text")
                        .HasColumnName("reading_url");

                    b.Property<string>("SpeakingAnswerUrl")
                        .HasColumnType("text")
                        .HasColumnName("speaking_answer_url");

                    b.Property<string>("SpeakingUrl")
                        .HasColumnType("text")
                        .HasColumnName("speaking_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("WritingAnswerUrl")
                        .HasColumnType("text")
                        .HasColumnName("writing_answer_url");

                    b.Property<string>("WritingUrl")
                        .HasColumnType("text")
                        .HasColumnName("writing_url");

                    b.HasKey("Id")
                        .HasName("pk_hsk_mock_tests");

                    b.ToTable("hsk_mock_tests", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.HskVocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ExampleMeaning")
                        .HasColumnType("text")
                        .HasColumnName("example_meaning");

                    b.Property<string>("ExamplePinyin")
                        .HasColumnType("text")
                        .HasColumnName("example_pinyin");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("text")
                        .HasColumnName("example_sentence");

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hanzi");

                    b.Property<string>("HskLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hsk_level");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pinyin");

                    b.Property<string>("WordType")
                        .HasColumnType("text")
                        .HasColumnName("word_type");

                    b.HasKey("Id")
                        .HasName("pk_hsk_vocabularies");

                    b.HasIndex("HskLevel")
                        .HasDatabaseName("ix_hsk_vocabularies_hsk_level");

                    b.HasIndex("HskLevel", "Hanzi")
                        .IsUnique()
                        .HasDatabaseName("ix_hsk_vocabularies_hsk_level_hanzi");

                    b.ToTable("hsk_vocabularies", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.HskVocabularyImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_count");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer")
                        .HasColumnName("imported_count");

                    b.Property<string>("JsonUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json_url");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("updated_count");

                    b.HasKey("Id")
                        .HasName("pk_hsk_vocabulary_imports");

                    b.ToTable("hsk_vocabulary_imports", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.HskVocabularyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LearnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("learned_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("integer")
                        .HasColumnName("vocabulary_id");

                    b.HasKey("Id")
                        .HasName("pk_hsk_vocabulary_progresses");

                    b.HasIndex("UserId", "VocabularyId")
                        .IsUnique()
                        .HasDatabaseName("ix_hsk_vocabulary_progresses_user_id_vocabulary_id");

                    b.ToTable("hsk_vocabulary_progresses", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.IeltsVocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Example")
                        .HasColumnType("text")
                        .HasColumnName("example");

                    b.Property<string>("ExampleMeaning")
                        .HasColumnType("text")
                        .HasColumnName("example_meaning");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("text")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("Phonetic")
                        .HasColumnType("text")
                        .HasColumnName("phonetic");

                    b.Property<string>("Topic")
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id")
                        .HasName("pk_ielts_vocabularies");

                    b.HasIndex("Topic")
                        .HasDatabaseName("ix_ielts_vocabularies_topic");

                    b.HasIndex("Word", "Meaning")
                        .IsUnique()
                        .HasDatabaseName("ix_ielts_vocabularies_word_meaning");

                    b.ToTable("ielts_vocabularies", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.IeltsVocabularyImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_count");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer")
                        .HasColumnName("imported_count");

                    b.Property<string>("JsonUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json_url");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("updated_count");

                    b.HasKey("Id")
                        .HasName("pk_ielts_vocabulary_imports");

                    b.ToTable("ielts_vocabulary_imports", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.LearningResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_learning_resources");

                    b.ToTable("learning_resources", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.LearningSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route");

                    b.HasKey("Id")
                        .HasName("pk_learning_sections");

                    b.ToTable("learning_sections", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("video_url");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer")
                        .HasColumnName("xp_reward");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_lessons_course_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_lessons_slug");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.ListenVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_name");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duration");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TranscriptUrl")
                        .HasColumnType("text")
                        .HasColumnName("transcript_url");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.Property<string>("YoutubeUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("youtube_url");

                    b.HasKey("Id")
                        .HasName("pk_listen_videos");

                    b.ToTable("listen_videos", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.MockTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collection_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HskUrl")
                        .HasColumnType("text")
                        .HasColumnName("hsk_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ListeningAnswerUrl")
                        .HasColumnType("text")
                        .HasColumnName("listening_answer_url");

                    b.Property<string>("ListeningUrl")
                        .HasColumnType("text")
                        .HasColumnName("listening_url");

                    b.Property<string>("ReadingAnswerUrl")
                        .HasColumnType("text")
                        .HasColumnName("reading_answer_url");

                    b.Property<string>("ReadingUrl")
                        .HasColumnType("text")
                        .HasColumnName("reading_url");

                    b.Property<string>("SpeakingAnswerUrl")
                        .HasColumnType("text")
                        .HasColumnName("speaking_answer_url");

                    b.Property<string>("SpeakingUrl")
                        .HasColumnType("text")
                        .HasColumnName("speaking_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("ToeicUrl")
                        .HasColumnType("text")
                        .HasColumnName("toeic_url");

                    b.Property<string>("WritingAnswerUrl")
                        .HasColumnType("text")
                        .HasColumnName("writing_answer_url");

                    b.Property<string>("WritingUrl")
                        .HasColumnType("text")
                        .HasColumnName("writing_url");

                    b.HasKey("Id")
                        .HasName("pk_mock_tests");

                    b.ToTable("mock_tests", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text")
                        .HasColumnName("audio_url");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<string>("IeltsBand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ielts_band");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("JsonUrl")
                        .HasColumnType("text")
                        .HasColumnName("json_url");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("QuestionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("questions_json");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("views_count");

                    b.Property<string>("VocabularyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vocabulary_json");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id")
                        .HasName("pk_stories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_stories_slug");

                    b.ToTable("stories", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.TestSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioKey")
                        .HasColumnType("text")
                        .HasColumnName("audio_key");

                    b.Property<double>("BandScore")
                        .HasColumnType("double precision")
                        .HasColumnName("band_score");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("ExamUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exam_url");

                    b.Property<DateTimeOffset?>("GradedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("graded_at");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TeacherFeedback")
                        .HasColumnType("text")
                        .HasColumnName("teacher_feedback");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_test_submissions");

                    b.HasIndex("UserId", "Skill")
                        .HasDatabaseName("ix_test_submissions_user_id_skill");

                    b.HasIndex("UserId", "SubmittedAt")
                        .HasDatabaseName("ix_test_submissions_user_id_submitted_at");

                    b.ToTable("test_submissions", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<DateTime>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("Streak")
                        .HasColumnType("integer")
                        .HasColumnName("streak");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.UserActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_activity_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_activity_logs_user_id");

                    b.ToTable("user_activity_logs", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Website", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<string>("RecommendedLevel")
                        .HasColumnType("text")
                        .HasColumnName("recommended_level");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_websites");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_websites_category_id");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_websites_language_id");

                    b.ToTable("websites", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Course", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedCourses")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_users_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Backend.Domain.Entities.HskVocabularyProgress", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hsk_vocabulary_progresses_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Backend.Domain.Entities.UserActivityLog", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_activity_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Website", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Category", "Category")
                        .WithMany("Websites")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_websites_categories_category_id");

                    b.HasOne("Backend.Domain.Entities.Language", "Language")
                        .WithMany("Websites")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_websites_languages_language_id");

                    b.Navigation("Category");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Category", b =>
                {
                    b.Navigation("Websites");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Course", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Language", b =>
                {
                    b.Navigation("Websites");
                });

            modelBuilder.Entity("Backend.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
