// <auto-generated />
using Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813161000_AddMockTestAnswerUrls")]
    partial class AddMockTestAnswerUrls
    {
    }
}
